spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/splitbill'
        username: root
        password: 1934Sai@
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER



