pipeline{
    agent any
    stages{
        stage('Build Jar file'){
            steps{
                script{
                    sh """
                       echo "Start building"
                       mvn clean build
                    """
                }
            }

        }
        stage('Docker build and push '){
            steps{
                script{
                   sh """
                      echo "Docker build and push"
                      docker build -t nooli/billbreaker:v1 .
                      """
                }
            }


        }
    }
}