pipeline{
    agent any
    environment {
        PATH="/Users/sainooli/.docker/bin:$PATH"
    }
    tools{
        maven 'M313'
    }
    stages{
        stage('Build Jar file'){
            steps{
                sh "echo $PATH"
                dir('billbreaker'){
                    script{
                        sh """
                           echo "Start building"
                           echo $PATH
                           mvn clean
                           mvn install
                           """
                    }
                }
            }
        }
        stage('Docker build and push '){
            steps{
                dir('billbreaker'){
                    script{
                        sh """
                            echo "Docker build and push"
                            echo $PATH
                             docker build -t nooli/billbreaker:v1 .
                        """
                    }
                }
            }
        }
    }
}